// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jmsmtgplqiezjcxrybcw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imptc210Z3BscWllempjeHJ5YmN3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgyMzEyNjMsImV4cCI6MjA3MzgwNzI2M30.E8U6OBfFhz_3w7aJihD6xOcSYGqz1Qhwa4KU_14db4A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});